version: '3.4'

services:
  todo-api:
    image: ${DOCKER_REGISTRY-}todoapi
    environment:
      - "ConnectionString=Data Source=192.168.19.196\\SQLEXPRESS2014;Initial Catalog=ToDo;User ID=SA;Password=SA4sql2014;MultipleActiveResultSets=True;"
    build:
      context: .
      dockerfile: ToDo-API/Dockerfile
    ports:
      - 5101:80

  todo-mvc-app:
    image: ${DOCKER_REGISTRY-}todomvcapp
    environment:
      - ToDoApiUrl=http://todo-api/
    build:
      context: .
      dockerfile: ToDo-Mvc-App/Dockerfile
